### ISSUE TITLE
当 umi-plugin-react 配置 locale:{enable: true,default: 'en-US',} ，运行时报错

### ISSUE THREAD

**Issue by Volcaner** [umijs/umi-example-ssr#6]
基于 umi-example-ssr 例子：
![image](https://user-images.githubusercontent.com/18595984/61037569-e8d77b00-a3fd-11e9-99c1-0adefde4a7de.png)
运行时 ./dist/umi.server.js 中报TypeError：
![image](https://user-images.githubusercontent.com/18595984/61037819-5be0f180-a3fe-11e9-8c85-d6960b3f2aa3.png)
将
```
// locale: {
//   enable: true,
//   default: 'en-US',
// },
```
去掉，就不报错了，但如果需要用到，应该怎么处理？

**Comment by ycjcl868** [comment]
已经修复

**Comment by Volcaner** [comment]
Thanks for your reply!
